server/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'questions#index'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  post   'votes'   => 'votes#create'

  resources :questions do
    resources :answers
  end

end

server/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :votes
  has_many :answers
  has_many :questions
end

server/app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  # POST /users
  def create
     @user = User.new(user_params)
    if @user.save
      session[:username] = @user.username
      redirect_to @user, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

server/app/helpers/users_helper.rb
module UsersHelper
  def current_user
    # @current_user ||= User.where(id: session[:user_id]).first if session[:user_id]
    current_user = User.find_by(username: session[:username])
  end

  def user_logged_in?
    session[:username] != nil
  end
end

server/app/views/users/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/users/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', question_answer_path(@question, @answer) %>

server/app/views/users/index.html.erb
<h2>Answer</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.title %></td>
        <td><%= answer.content %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Answer', new_answer_path %>

server/app/views/users/new.html.erb
<h1>Signup</h1>
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>

  Username: <%= f.text_field :username, class: 'form-control' %>
  Password: <%= f.password_field :password, class: 'form-control' %>
  Password Confirmation: <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.submit "Submit", class: "btn btn-primary" %>

<% end %>
</div>

server/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>