server/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'questions#index'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  post   'votes'   => 'votes#create'

  resources :questions do
    resources :answers
  end

end

server/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable
end

server/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]


  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all.order(score: :asc)
  end

  # GET /answers/1
  # GET /answers/1.json
  def show

    p @question = @answer.question
  end

  # GET /answers/new
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    p @answer
    p @question
  end

  # GET /answers/1/edit
  def edit
    p @answer
    p @question = @answer.question
  end

  # POST /answers
  # POST /answers.json
  def create
    @question = Question.find(params[:question_id])
    p @question
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question), notice: 'Answer was successfully created.'
  end


  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_answer_url, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:title, :content)
    end
end

server/app/helpers/answers_helper.rb
module AnswersHelper
end

server/app/views/answers/_form.html.erb
<div class="well cf" style="clear: right;">
  <%= form_for [@question, @question.answers.build], html: {:class => "form-answer"} do |f| %>
  <% if @answer %>
    <% if @answer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

        <ul>
        <% @answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

  <legend>Your Answer</legend>

  <div class="form-group">
    <label for="">Answer Title:</label>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group ">
    <label for="">Answer Content:</label>
    <%= f.text_area :content, :class => "form-control" %>
  </div>
    <%= f.submit :class => "btn btn-primary" %>
<% end %>

</div>

server/app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', question_answer_path(@question, @answer) %>

server/app/views/answers/index.html.erb
<h2>Answer</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.title %></td>
        <td><%= answer.content %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Answer', new_answer_path %>

server/app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

server/app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @answer.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>


<%= link_to 'Edit', edit_question_answer_path(@question, @answer) %> |