server/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'questions#index'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  post   'votes'   => 'votes#create'

  resources :questions do
    resources :answers
  end

end

server/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable
end

server/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :allow_cross_domain

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order(created_at: :desc)
    p @questions
    render json: @questions
    # id: 10, title: "Veritatis error sunt rerum in autem nesciunt lauda...", content: "Reprehenderit molestiae laudantium labore voluptas...", score: 0,
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.all.order(score: :desc)
    @questions = Question.all.order(created_at: :desc)
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    if @question.save
      p @question
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content)
    end

    def allow_cross_domain
      headers['Access-Control-Allow-Origin'] = '*'
       headers['Access-Control-Request-Method'] = 'POST, GET, PUT, PATCH, DELETE, OPTIONS'
       headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    end
end

server/app/helpers/questions_helper.rb
module QuestionsHelper
end

server/app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

server/app/views/questions/index.html.erb
<div class="post-wrapper">
  <div class="row question-wrapper">
    <div class="col-md-9 ">
      <%= link_to 'New Question', new_question_path, :class => "btn btn-primary pull-right", :style => "margin-top: 16px;" %>

      <h1>Recent Questions</h1>



      <% @questions.each do |question_item| %>
      <div id="question-<%= question_item.id %>"class="post question cf">
        <div class="vote">

          <%= button_to "", votes_path(vote: {vote_value: 1, votable_type: "Question", votable_id: question_item.id}), :class => "vote-button vote-up", method: :post %>

            <div class="vote-count"><%= question_item.score %></div>

          <%= button_to "", votes_path(vote: {vote_value: -1, votable_type: "Question", votable_id: question_item.id}), :class => "vote-button vote-down", method: :post %>

        </div>
        <div class="question-body">
          <h4 class="question-heading"><%= link_to question_item.title, question_item %></h4>
          <p><%= question_item.content %></p>

          <div class="btn-group btn-group-sm">
            <%= link_to "Show", question_path(question_item), :class => "btn  btn-default", :id => "my-id" %>
            <%= link_to "Edit", edit_question_path(question_item), :class => "btn btn-default", :id => "my-id" %>
            <%= link_to'Delete', question_path(question_item), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default", :id => "my-id" %>
          </div>

        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

server/app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

server/app/views/questions/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= notice %>
  </div>
<% end %>

  <div class="post-wrapper">

    <div class="row question-wrapper">
      <div class="col-md-9 ">

        <div id="question-<%= @question.id %>" class="post question cf">
          <div class="vote">

            <%= button_to "", votes_path(vote: {vote_value: 1, votable_type: "Question", votable_id: @question.id}), :class => "vote-button vote-up", method: :post %>

            <div class="vote-count"><%= @question.score %></div>

            <%= button_to "", votes_path(vote: {vote_value: -1, votable_type: "Question", votable_id: @question.id}), :class => "vote-button vote-down", method: :post %>

          </div>
          <div class="post-body">
            <h1><%= @question.title %></h1>
            <p><%= @question.content %></p>
            <%= link_to "Edit", edit_question_path(@question) , :class => "btn btn-default"%>
            <%= link_to "Delete", question_path, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %>
          </div>
        </div>

      </div>
    </div>

    <div class="row answer-wrapper">
      <div class="col-md-9">
        <%= link_to 'New Answer', new_question_answer_path(@question), :class => "btn btn-primary pull-right answer-new-button", :style => "margin-top: 15px;" %>

        <div class="answer-form" style="display: none">
          <%= render 'answers/form' %>
        </div>

        <h3><%= @answers.count %> Answers</h3>

        <% @answers.each do |answer| %>
        <div id="answer-<%= answer.id %>" class="post answer cf">
          <div class="vote">

            <%= button_to "", votes_path(vote: {vote_value: 1, votable_type: "Answer", votable_id: answer.id}), :class => "vote-button vote-up", method: :post %>

            <div class="vote-count"><%= answer.score %></div>

            <%= button_to "", votes_path(vote: {vote_value: -1, votable_type: "Answer", votable_id: answer.id}), :class => "vote-button vote-down", method: :post %>

          </div>

          <div class="post-body">
            <h4><%= answer.title %></h4>
            <p><%= answer.content %></p>
            <%= link_to "Show", question_answer_path(@question, answer) , :class => "btn btn-default pull-right" %>
          </div>

        </div>
        <% end %>
      </div>
    </div>

  </div>